# Instance name
name: "QuantizationAwareTraining"

# How many GPUs to train/test
n_gpu: 1

# Random seed
random_seed: 2333

# Model
arch:
    type: "cifar_efficientnetb0"         # name in `model` package
    args: {pretrained: false, num_classes: 100, 
          bn_momentum: 0.9}
    load_from_pth: "saved/models/Classification/1208_143000/checkpoint-epoch170.pth"      # path to pretrained .pth file

# Dataloaders
dataloaders:
    train:
        type: "CIFAR100"    # name in data_loader/data_loaders.py
        args:
            data_dir: "E:/data/dataset/CIFAR100"
            training: true
            batch_size: 128
            shuffle: true
            num_workers: 4
    test:
        type: "CIFAR100"    # name in data_loader/data_loaders.py
        args:
            data_dir: "E:/data/dataset/CIFAR100"
            training: false
            batch_size: 1024
            shuffle: false
            num_workers: 0

# Options for quantization
quantization:
    weight:
        enable: true
        type: "LSQ"
        args:
            n_bits: 8
            signed: true
    input:
        enable: true
        type: "LSQ"
        args:
            n_bits: 8
            signed: false
    exclude_layers: ["stage1.0.conv", "FC"]           # name of layers to exclude (with fp32 precision), regular expression supported
    override_options:            # override options for some specified layers
        - layers: []
          options:
              weight: {args: {n_bits: 8, signed: false}}
              input: {type: "minmax_tensor", args: {n_bits: 8, signed: false}}
        - layers: []    # name of layers to override options, regular expression supported
          options:
              weight: {args: {n_bits: 8}}
              input: {args: {n_bits: 8}}

# Options for training
optimizer:
    type: "SGD"               # name in torch.optim
    args:
        nesterov: true
        lr: 0.01
        weight_decay: 5e-3
        momentum: 0.9
loss: "cross_entropy_loss"               # name in trainer/loss
metrics:                       # name in trainer/metrics
    - "accuracy"
    - "top5_acc"
lr_scheduler:
    type: "CosineAnnealingLR"            # name in torch.optim.lr_scheduler
    args:
        T_max: 90
    #type: "MultiStepLR"            # name in torch.optim.lr_scheduler
    #args:
    #    milestones: [60, 120, 160]
    #    gamma: 0.2
trainer:
    epochs: 90
    save_dir: "saved/"
    save_period: 1
    verbosity: 2
    monitor: "max val_accuracy"
    #early_stop:
    tensorboard: false
    #update_qparams_period: 1000     # step period to update quantized params(scales and offsets)
    freeze_bn: false                 # if True, statistics parameters of BN layers will be frozen
